name: forui_base
description: "Forui Base Experimental"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^16.2.0
  forui: ^0.15.1
  flutter_hooks: ^0.21.3+1
  gap: ^3.0.1
  cached_network_image: ^3.4.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  flutter_riverpod: ^3.0.0-dev.17
  retrofit: ^4.7.2
  dartz: ^0.10.1
  flutter_svg: ^2.2.0
  skeletonizer: ^2.1.0+1
  equatable: ^2.0.7
  latlong2: ^0.9.1
  flutter_debouncer: ^2.0.0
  hooks_riverpod: ^3.0.0-dev.17
  forui_hooks: ^0.15.0
  flutter_map: ^8.2.1
  url_launcher: ^6.3.2
  flutter_launcher_icons: ^0.14.4
  flutter_map_animations: ^0.9.0
  envied: ^1.2.0
  jiffy: ^6.4.3
  stack_trace: ^1.12.1
  infinite_scroll_pagination: ^5.1.0
  gal: ^2.3.2
  intl: ^0.20.2
  fl_chart: ^1.0.0
  shared_preferences: ^2.5.3
  webview_flutter: ^4.13.0
  fluttertoast: ^8.2.12
  hive_ce: ^2.11.3
  hive_ce_flutter: ^2.3.2
  logger: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.7.0
  freezed: ^3.2.0
  json_serializable: ^6.9.5
  riverpod_lint: ^3.0.0-dev.17
  custom_lint: ^0.8.0
  riverpod_generator: ^3.0.0-dev.17
  pretty_dio_logger: ^1.4.0
  retrofit_generator: '^10.0.0'
  envied_generator: ^1.2.0
  hive_ce_generator: ^1.9.3

flutter:

  uses-material-design: true
  generate: true

  assets:
    - .env
    - assets/images/
    - assets/icons/

gen-l10n:
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart
  output-class: AppLocalizations
  preferred-supported-locales: [en, id, es]
  untranslated-messages-file: lib/l10n/untranslated.txt