import 'package:forui/forui.dart';
import 'package:forui_base/shared/data/models/app/tile_data.dart';

final List<TileData> implementBacklogsStatic = [
  TileData(
    icon: FIcons.fingerprint,
    title: 'Local Biometric',
    subtitle: "https://pub.dev/packages/local_auth",
    status: false,
  ),
  TileData(
    icon: FIcons.fingerprint,
    title: 'Push Notification',
    subtitle: "Realtime push notification",
    status: false,
  ),
  TileData(
    icon: FIcons.fingerprint,
    title: 'Websocket implement',
    subtitle: "Realtime push notification",
    status: false,
  ),
  TileData(
    icon: FIcons.text,
    title: 'Rich text editor (WYSIWYG)',
    subtitle: 'flutter_quill',
    status: false,
  ),
  TileData(
    icon: FIcons.mapPin,
    title: 'Tracking Position',
    subtitle:
        'Tracking position with geolocator and move position on flutter_map',
    status: false,
  ),
  TileData(
    icon: FIcons.play,
    title: 'Animated Text Kit',
    subtitle: 'animated_text_kit',
    status: false,
  ),
  TileData(
    icon: FIcons.network,
    title: 'Network Connectivity',
    subtitle: 'connectivity_plus',
    status: false,
  ),
  TileData(
    icon: FIcons.database,
    title: 'Drift',
    subtitle: 'http://github.com/simolus3/drift',
    status: false,
  ),
  TileData(
    icon: FIcons.battery,
    title: 'Batery Information',
    subtitle: 'https://pub.dev/packages/battery_plus',
    status: false,
  ),
  TileData(
    icon: FIcons.play,
    title: 'Flutter Animate',
    subtitle: 'https://pub.dev/packages/flutter_animate',
    status: false,
  ),
  TileData(
    icon: FIcons.refreshCcw,
    title: 'Background Service',
    subtitle: 'Still run while app closed',
    status: false,
  ),
  TileData(
    icon: FIcons.shieldCheck,
    title: 'Safe Device Checker',
    subtitle: 'Jailbroken, root, emulator and mock location detection',
    status: false,
  ),
  TileData(
    icon: FIcons.phone,
    title: 'Device Locale',
    subtitle: 'Gets the device locale data (devicelocale)',
    status: false,
  ),
  TileData(
    icon: FIcons.camera,
    title: 'Camera Plugin',
    subtitle: 'https://pub.dev/packages/camera',
    status: false,
  ),
  TileData(
    icon: FIcons.video,
    title: 'Youtube Player iFrame',
    subtitle: 'youtube_player_iframe',
    status: false,
  ),
  TileData(
    icon: FIcons.settings,
    title: 'ENVied',
    subtitle: 'Handle environment variables',
    status: false,
  ),
  TileData(
    icon: FIcons.book,
    title: 'PDF Viewer',
    subtitle: 'https://pub.dev/packages/pdfrx',
    status: false,
  ),
  TileData(
    icon: FIcons.qrCode,
    title: 'QR Code Scanner',
    subtitle: 'https://pub.dev/packages/qr_code_scanner_plus',
    status: false,
  ),
  TileData(
    icon: FIcons.camera,
    title: 'Camera With Overlay',
    subtitle: 'Show camera with overlay to guide user',
    status: false,
  ),
  TileData(
    icon: FIcons.idCard,
    title: 'Device ID (UDID)',
    subtitle: 'https://pub.dev/packages/flutter_udid',
    status: false,
  ),
  TileData(
    icon: FIcons.image,
    title: 'Image Picker',
    subtitle: 'https://pub.dev/packages/image_picker',
    status: false,
  ),
  TileData(
    icon: FIcons.brain,
    title: 'Permission Handler',
    subtitle: 'https://pub.dev/packages/permission_handler',
    status: false,
  ),
  TileData(
    icon: FIcons.file,
    title: 'File Picker',
    subtitle: 'https://pub.dev/packages/file_picker',
    status: false,
  ),
  TileData(
    icon: FIcons.phone,
    title: 'Device Info',
    subtitle: 'https://pub.dev/packages/device_info_plus',
    status: false,
  ),
  TileData(
    icon: FIcons.reply,
    title: 'Share Content',
    subtitle: 'https://pub.dev/packages/share_plus',
    status: false,
  ),
  TileData(
    icon: FIcons.book,
    title: 'Logger',
    subtitle:
        'https://pub.dev/packages/logger, https://pub.dev/packages/logging',
    status: false,
  ),
  TileData(
    icon: FIcons.locate,
    title: 'Geolocator',
    subtitle: 'https://pub.dev/packages/geolocator',
    status: false,
  ),
  TileData(
    icon: FIcons.key,
    title: 'Social Auth',
    subtitle: 'Auth with google etc..',
    status: false,
  ),
  TileData(
    icon: FIcons.externalLink,
    title: 'App Links',
    subtitle: 'Deep Links',
    status: false,
  ),
  TileData(
    icon: FIcons.code,
    title: 'XML',
    subtitle: 'Parser XML',
    status: false,
  ),
  TileData(
    icon: FIcons.globe,
    title: 'Geocoding',
    subtitle: 'Parser XML',
    status: false,
  ),
  TileData(
    icon: FIcons.database,
    title: 'Firebase Remote Config',
    subtitle: 'https://pub.dev/packages/firebase_remote_config',
    status: false,
  ),
  TileData(
    icon: FIcons.image,
    title: 'Blurhash',
    subtitle: 'https://pub.dev/packages/flutter_blurhash',
    status: false,
  ),
  TileData(
    icon: FIcons.barcode,
    title: 'Barcode',
    subtitle: 'https://pub.dev/packages/barcode',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: 'Record Audio',
    subtitle: 'https://pub.dev/packages/record',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: 'Vibration',
    subtitle: 'https://pub.dev/packages/vibration',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: 'Text To Speech',
    subtitle: 'https://pub.dev/packages/flutter_tts',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: 'Map Launcher',
    subtitle: 'https://pub.dev/packages/map_launcher',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: 'Supabase Client',
    subtitle: 'https://pub.dev/packages/supabase_flutter',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: 'AndroidIntent',
    subtitle: 'https://pub.dev/packages/android_intent_plus',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: 'Hive CE',
    subtitle: 'https://pub.dev/packages/hive_ce',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: 'Payments',
    subtitle: 'https://pub.dev/packages/pay',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: 'Image Galery Saver',
    subtitle:
        'https://pub.dev/packages/image_gallery_saver, https://pub.dev/packages/gal',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: 'Internet Connection',
    subtitle: 'https://pub.dev/packages/internet_connection_checker_plus',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: 'Leak Tracker',
    subtitle: 'https://pub.dev/packages/leak_tracker',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: 'File Selector',
    subtitle: 'https://pub.dev/packages/file_selector',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: 'Background Fetch',
    subtitle: 'https://pub.dev/packages/background_fetch',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: 'Home Widget',
    subtitle: 'https://pub.dev/packages/home_widget',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: 'Card Swiper',
    subtitle: 'https://pub.dev/packages/flutter_card_swiper',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: 'Crop Image',
    subtitle: 'crop_your_image, image_cropper',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: 'MQTT Client',
    subtitle: 'https://pub.dev/packages/mqtt_client',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: 'Background Downloader',
    subtitle: 'https://pub.dev/packages/background_downloader',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: 'Add To Calendar',
    subtitle: 'https://pub.dev/packages/add_2_calendar',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: 'Link Preview',
    subtitle: 'https://pub.dev/packages/flutter_link_previewer',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: 'Cron/Scheduler',
    subtitle: 'https://pub.dev/packages/cron',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: 'Pro Image Editor',
    subtitle: 'https://pub.dev/packages/pro_image_editor',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: 'Native Drag and Drop',
    subtitle: 'https://pub.dev/packages/super_drag_and_drop',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: 'Super Clipboard',
    subtitle: 'https://pub.dev/packages/super_clipboard',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: 'Audio',
    subtitle: 'https://pub.dev/packages/flutter_soloud',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: 'No Screenshoot',
    subtitle: 'https://pub.dev/packages/no_screenshot',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: 'Timeline',
    subtitle: 'https://pub.dev/packages/timelines_plus',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: 'Filesize',
    subtitle: 'https://pub.dev/packages/filesize',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: "Displaying device's current location",
    subtitle: 'https://pub.dev/packages/flutter_map_location_marker',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: "Drag and Drop GridView",
    subtitle: 'https://pub.dev/packages/flutter_reorderable_grid_view',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: "Drawing Board",
    subtitle: 'https://pub.dev/packages/flutter_drawing_board',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: "Type Writer Text",
    subtitle: 'https://pub.dev/packages/typewritertext',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: "JSON View",
    subtitle: 'https://pub.dev/packages/flutter_json_view',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: "To know the status of the call",
    subtitle: 'https://pub.dev/packages/phone_state',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: "Screen Capture Event",
    subtitle: 'https://pub.dev/packages/screen_capture_event',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: "Webview",
    subtitle: 'webview_flutter_plus, webview_flutter',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: "Image Painter",
    subtitle: 'https://pub.dev/packages/image_painter',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: "PIP View",
    subtitle: 'https://pub.dev/packages/pip_view',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: "Shared Preferences",
    subtitle: 'https://pub.dev/packages/shared_preferences',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: "Contact Picker",
    subtitle: 'https://pub.dev/packages/flutter_native_contact_picker',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: "Video Player",
    subtitle: 'http://pub.dev/packages/video_player',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: "Secure Storage",
    subtitle: 'http://pub.dev/packages/flutter_secure_storage',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: "Package Rename",
    subtitle: 'https://pub.dev/packages/package_rename',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: "FL Chart",
    subtitle: 'https://pub.dev/packages/fl_chart',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: "Staggered GridView",
    subtitle: 'https://pub.dev/packages/flutter_staggered_grid_view',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: "Thumbnailer",
    subtitle: 'https://pub.dev/packages/thumbnailer',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: "Archive",
    subtitle: 'https://pub.dev/packages/archive',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: "QR Render",
    subtitle: 'https://pub.dev/packages/qr_flutter',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: "Mobile Ads",
    subtitle: 'https://pub.dev/packages/google_mobile_ads',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: "Slideable",
    subtitle: 'https://pub.dev/packages/flutter_slidable',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: "Create PDF",
    subtitle: 'https://pub.dev/packages/pdf',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: "Timeago",
    subtitle: 'https://pub.dev/packages/timeago',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: "Slivertools",
    subtitle: 'https://pub.dev/packages/sliver_tools',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: "Mask Text Input",
    subtitle: 'https://pub.dev/packages/mask_text_input_formatter',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: "Printing",
    subtitle: 'https://pub.dev/packages/printing',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: "Torch",
    subtitle: 'https://pub.dev/packages/torch_light',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: "Sticky headers with a sliver as a child",
    subtitle: 'https://pub.dev/packages/flutter_sticky_header',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: "Diff Text",
    subtitle: 'https://pub.dev/packages/pretty_diff_text',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: "Mysql CLient",
    subtitle: 'https://pub.dev/packages/mysql_client',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: "Color Picker",
    subtitle: 'https://pub.dev/packages/flutter_colorpicker',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: "Open File",
    subtitle: 'open_file, open_filex',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: "GraphQL",
    subtitle: 'https://pub.dev/packages/graphql_flutter',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: "Widgetbook",
    subtitle: 'https://pub.dev/packages/widgetbook',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: "Stripe",
    subtitle: 'https://pub.dev/packages/flutter_stripe',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: "Back Button Interceptor",
    subtitle: 'https://pub.dev/packages/back_button_interceptor',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: "Workmanager",
    subtitle: 'https://pub.dev/packages/workmanager',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: "Downloader",
    subtitle: 'https://pub.dev/packages/flutter_downloader',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: "Dotted Line",
    subtitle: 'https://pub.dev/packages/dotted_line',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: "Call Log",
    subtitle: 'https://pub.dev/packages/call_log',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: "Contact Manage",
    subtitle: 'https://pub.dev/packages/flutter_contacts',
    status: false,
  ),
  TileData(
    icon: FIcons.package,
    title: "OCR",
    subtitle: 'https://pub.dev/packages/google_mlkit_text_recognition',
    status: false,
  ),
];

final doneBacklogsStatic = [
  TileData(
    icon: FIcons.galleryHorizontal,
    title: 'Infinite Scroll Pagination',
    subtitle: 'https://pub.dev/packages/infinite_scroll_pagination',
    status: false,
  ),
];

final List<TileData> checkBacklogsStatic = [
  TileData(
    icon: FIcons.eye,
    title: 'Flutter Tailwind UI',
    subtitle: 'https://github.com/tazatechnology/flutter-tailwind-ui',
    status: false,
  ),
  TileData(
    icon: FIcons.eye,
    title: 'Yaru',
    subtitle: 'https://github.com/ubuntu/yaru.dart',
    status: false,
  ),
  TileData(
    icon: FIcons.eye,
    title: 'Fluent UI',
    subtitle: 'https://github.com/bdlukaa/fluent_ui',
    status: false,
  ),
  TileData(
    icon: FIcons.eye,
    title: 'Next UI',
    subtitle: 'https://github.com/iamEtornam/NextUi',
    status: false,
  ),
  TileData(
    icon: FIcons.eye,
    title: 'Liquid Glass UI',
    subtitle: 'https://github.com/santhosh-ceo/liquid_glass_ui',
    status: false,
  ),
  TileData(
    icon: FIcons.eye,
    title: 'Windows XP UI',
    subtitle: 'https://github.com/jessimalak/xp_ui',
    status: false,
  ),
  TileData(
    icon: FIcons.eye,
    title: 'Flutter95',
    subtitle: 'https://github.com/miquelbeltran/flutter95',
    status: false,
  ),
  TileData(
    icon: FIcons.eye,
    title: 'NeuBrutal Kit',
    subtitle: 'https://github.com/Mani821/neubrutal_kit',
    status: false,
  ),
];

final List<TileData> librariesBacklogsStatic = [
  TileData(
    icon: FIcons.box,
    title: 'Lorem',
    subtitle:
        'Ullamco dolor ut dolor do reprehenderit aliqua ad ea ex qui ea nostrud cillum.',
    status: false,
  ),
];
