// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:forui_base/shared/data/models/hive/key_value.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(KeyValueAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(KeyValueAdapter());
  }
}
